- FilterReview/FilterReview.js
- FilterReview/index.html
Post filter estimate from pre-filter data and filter configuration:
Bode plots:
This does make it all quite slow again, the filter evaluation takes ages, certainly a fair bit of scope for speeding it up. I would also like to use a smaller frequency step on the bode plots (more like filter tool), currently they match the FFT's because that is what we need to estimate post filter. But that would make it extremely slow. The big frequency steps also mean that the phase unwrap can come out wrong since we can get correct changes of more than 180 deg.
> FilterReview: add post filter estimate and bode plots 

- FilterReview/FilterReview.js
The `math` lib we have been using is excellent for ease of use because it figures out types by itself. So we can multiply scalars, arrays and matrixs with each other using a single function. However this versatility makes it slow, this moves to use helpers and the built in `Math` functions as much as possible, depending on the log can be up to three or four times faster. 
I think this more or less completes the low hanging speed ups in the tool. The next place to look would be the log parser.
We do still use a bunch of memory, that means large logs can fail, I'm not really sure the best way to improve that.
> FilterReview: move away from `math` lib as much as possible for speed

- FilterReview/FilterReview.js
- FilterReview/index.html
This should be quite a nice speed up, it also reorders things so the log itself can be freed before we start using more memory in the FFT calculation. This also adds a new filter re-calc button that is closer to the filter config to avoid the need for constant scrolling.
> FilterReview: more speed and less memory, also add a new re-calc button

- FilterTool/filters.js
- FilterTool/index.html
This moves the filter tool over to plotly to match the filter review tool. This simplifies the code quite a bit. The inter-activeness of plotly also means we can remove the need to manually give a max freq and phase lag, we plot the full range and the user can manually zoom. Plotting the full range does take a bit longer to calculate, but its not too bad.
All the axis labels and scales work as before.
We do loose the auto scaling that the old plots did, but I don't think that is a big issue. Old:
New:
> FIlterTool: move to plotly

- FilterTool/filters.js
- FilterTool/index.html
This adds buttons to show the contributions of each filter in the total result. For example:
This allows the user to see that a frequency X filter Y is doing most of the work so that is the one to adjust.
Same for the PIDs:
> FitlerTool: add show individual functionality to filters and PIDs

- FilterReview/FilterReview.js
- FilterReview/index.html
This adds a button down at the bottom to open the current filter setup in the filter tool.
The filter tool allows viewing of individual components (https://github.com/ArduPilot/WebTools/pull/21) that would be impractical to show over the whole log in the filter review tool.
> FilterReview: add button to open in filter tool

- FilterReview/FilterReview.js
- FilterReview/index.html
This adds a aliasing view and loop rate param:
When selected the whole frequency range is folded down into the niquist of the loop rate, this represents the noise the control loops actually see. For example this is the normal sub 200hz:
With aliasing on:
The extra peaks are reflections from higher frequencies:
There is also the option to show only the aliasing, this removes the frequencies lower than the niquist and only shows the aliased signals reflected down from higher frequencies, this should be as close to 0 as posible.
> FilterReview: Add aliasing view

- FilterReview/FilterReview.js
- FilterReview/index.html
- FilterReview/params.json
- FilterTool/filters.js
- FilterTool/index.html
- FilterTool/params.json
- Libraries/ParameterMetadata.js
This adds layout generation from param metadata in a json format. A value input element is used as the key to add a label, units, dropdown and bit checkboxes around. Each input should be in a separate paragraph. New helper functions should be used to set or hide so all bits stay in sync. Hover over for param descriptions.
FilterTool is moved over to the same layout as the FilterReviewTool with notches side by side. Otherwise the new options make the page quite long since rather than hiding we just disable.
Currently this use a manually generated json file for each script, it is cut down to minimize size only including the params that are needed. In the future it would be nice to auto generate this.
> Layout generation from param metadata

- FilterReview/FilterReview.js
Data missing form ESC instances causes the tool to fail. This fixes that.
> FilterReview: deal with missing data from a ESC leading to discontinuous instances

- FilterReview/FilterReview.js
- FilterReview/index.html
If it can workout the primary gyro from params the tool will now highlight that sensor with a green box and adding "Primary". It will then only plot that sensor by default, this makes it less overwhelming on first plot.
This also fixes a bug there the post filter estimate would use the incorrect value if the reference was not set, now it correctly defaults to a static filter at the set frequency.
> FilterReview: bug fixes and highlight the primary gyro

- HardwareReport/HardwareReport.js
This allows the tool to handle logs from older versions.
> HardwareReport: better cope with older logs

- FilterReview/FilterReview.js
js pass by reference behavior here was resulting in the updated values getting put back in to the stored reference, this meant that the source data had the min freq constrain applied so the min freq could not be lowered later. The fix is to use a new array for the data to break that link.
> FilterReview: Fix ESC and FFT sticky min freq

- FilterReview/index.html
- HardwareReport/index.html
- Libraries/OpenIn.js
- PIDReview/index.html
Many thanks to @Williangalvani for working out how we could do this and adding support to plot.ardupilot, https://github.com/ArduPilot/UAVLogViewer/pull/403
This adds buttons to pass logs back and forth between tools, once a log is loaded a drop down will become available to load the log in a tool in a new window.
Note that this has only be tested locally, it seems to work between tools, but not to UAV Log Viewer.
> All: add new "open in" functionality to pass logs bettween tools

- FilterReview/index.html
- HardwareReport/HardwareReport.js
- HardwareReport/index.html
- Libraries/LoadingOverlay.js
- PIDReview/PIDReview.js
- PIDReview/index.html
This adds a simple loading overlay that shows while the log is loading. No fancy spinner or anything yet. 
Just dims the main page and adds "loading" in the middle of the window. 
Logs only, where a param file is loaded its so quick that there is no point, so filter tool and hardware review from param file are not changed.
> all: add loading overlay for logs

- FilterReview/FilterReview.js
When using fast sampling using the logged gyro rate to apply the filters at is not correct. The logging rate is a better estimate of the rate the filters are actually applied at.
Before there is a amplitude error that increases with frequency:
After results are extremely close up to the the last 100Hz or so:
> FilterReview: use correct sample rate for post filter estimate

- FilterReview/FilterReview.js
- FilterReview/index.html
- FilterTool/filters.js
- FilterTool/index.html
- Libraries/Array_Math.js
- Libraries/fft.js
- PIDReview/PIDReview.js
- PIDReview/index.html
We were missing a array mean and array range function. This adds those to our `Array_Math` lib removing the dependency on `mathjs`.
> All: add missing methods to allow removal of mathjs package

- FilterReview/FilterReview.js
After https://github.com/ArduPilot/WebTools/pull/69 I almost immediately found a log where the new estimate is much worse, this goes back to using 0. I think we could do it properly but I need to do some more reading.
> FilterReview: go back to 0 quantisation noise for raw logging

- FilterReview/FilterReview.js
`INS_LOG_BAT_OPT` don't propagate to logging in some cases (I have not looked into this on the AP side). Rather than failing to plot with a error this now alerts and then plots as usual.
> FilterReview: infer pre-post from number of intances if INS_LOG_BAT_OPT is not set.

- Libraries/ParameterMetadata.js
param.onchange() doesn't exist, impacts harmonic tick boxes
> stopped fault in FilterTool

- PIDReview/PIDReview.js
The scaling stuff means the target and actually can't be used to calculate the error, which might make the plots look a little odd, but all the maths should still work.
> PIDReview: enable for plane forward flight PIDs

- FilterTool/filters.js
- FilterTool/index.html
The "get link" button was missing mode and enabled as they are now "select" types rather than "input" and gyro sample rate was missed because the ID and name did not match.
> FilterTool: fix "get link" formatting and parsing.

- MAGFit/magfit.js
Fixes https://github.com/ArduPilot/WebTools/issues/83
In the log battery current was all zero, this would be the case if the monitor could read current but was not configured to. No variation in the current causes the matrix to be rank deficient and the solver errors out. 
I also have a patch that puts a try - catch around the solve, that would also fix but may prevent the reporting of such issues in the future.
> MAGFit: ignore battery current if all zero

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
Adds download links for any mission or fence found in the log.
It will attempt not to provide multiple files for the same thing as Mission planner sometimes does.
> HardwareReport: add downloading of missions and fence

- HardwareReport/HardwareReport.js
Does what it says on the tin.
Would like to have param view to show the full bitmask, but for that to work we need to make the tool build type aware so we load the correct param documentation.
> HardwareReport: be annoying if arming checks are disabled

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
Adds a pie chart that shows the size and percentage of each log message. 
Needs https://github.com/Williangalvani/JsDataflashParser/pull/7
> HardwareReport: add log stats pie chart

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
This moves the plots after the params, so it now looks like this:
It is also now possible to collapse the plots:
Although currently all the sections default to not collapsed. 
In the future I would like to do some sort of auto analysis so that plots can only be shown if there is something interesting in them.
> HardwareReport: move plots after prams and add option to collapse 

- HardwareReport/HardwareReport.js
Fixup for https://github.com/ArduPilot/WebTools/pull/100, the `Flags` field is quite new, now works with older logs.
> HardwareReport: only try to use rally point flags field if available

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
Adds decoding of internal errors from `PM` or `MON` logs.
> HardwareReport: add internal errors

- HardwareReport/HardwareReport.js
- PIDReview/PIDReview.js
A couple of easy fixes that lets a log from 4.0 load. We were looking for log fields that were mission in hardware report and looking for params that are missing in PID Review.
> Hardware Report and PIDReview: fixes for 4.0

- FilterReview/FilterReview.js
- FilterReview/index.html
This is more because its useful to verify the tool than because its useful for log review. This allows the tools estimated notch center frequencies to be compared to the real notch frequencies from log.  
This adds a new logged check box and a tool top for the notch tracking box.
Before any parameter changes the logged should agree with the estimated.
> FilterReview: add the ability to plot logged notch frequency on spectogram

- HardwareReport/HardwareReport.js
If using "open" we don't have the log name, currently we end up with odd names in that case as it try to use the extension and then adds `.txt`.
> HardwareReport: use a generic log name if none is avalable

- HardwareReport/HardwareReport.js
I was checking for the presence of compass not baro.
> HardwareReport: fix baro indexing bug

- FilterReview/FilterReview.js
- HardwareReport/HardwareReport.js
- MAGFit/magfit.js
- PIDReview/PIDReview.js
This saves quite a bit of memory meaning you can load larger logs before your browser gives up. Particularly HardwareReport which was loading most of the messages up front.
> All: only load log messages when needed and delete when done

- MAGFit/magfit.js
The goal was a error, but not a code one.
> MAGFit: fix no attitude selected error

- FilterReview/index.html
This adds a link to https://ardupilot.org/copter/docs/common-raw-imu-logging.html in the intro paragraph.
It would be nice to also put the link in the alert window you get if the correct log messages are not found, but links are not allowed in a alert box. We could switch to something else, but that would be a bigger job.
> FilterReview: add link to raw logging setup page on wiki

- MAGFit/index.html
- MAGFit/magfit.js
Some fixes from https://github.com/ArduPilot/WebTools/issues/120
This removes "predicted" from the intro instead using "expected" inline with the rest of the tool. "fit" is replaced with "calibration" throughout.
A note is added to the no motor comp tool tip to give a clue about any grayed out options.
> MAGFit: improve text and tool tip wording.

- FilterReview/FilterReview.js
This removes the requirement to have `IMU` in the log. if available it is used to get the gyro rate.
> FilterReview: allow to work without IMU message for gyro rate

- HardwareReport/HardwareReport.js
Fixup for https://github.com/ArduPilot/WebTools/pull/128, checks there is a device at the address before trying to get it.
> HardwareReport: fix print for missing CAN devices

- FilterReview/FilterReview.js
Fix for https://github.com/ArduPilot/WebTools/issues/130, the log had ESC's 1,2,3,4 rather than 0,1,2,3 so the indexing got messed up. Seems like we don't need the `instance_map`, we don't ever display ESC numbers, so it doesn't really matter if they don't match the log.
> FilterReview: fix ESC indexing

- FilterReview/FilterReview.js
We only have the UI elements for 3 instances, so trying to load a log with more than 3 instances currently makes everything fall over. This changes to ignore those higher instances. Support for more instances added to todo list.
> FilterReview: Ignore IMUs instances >= 3

- HardwareReport/HardwareReport.js
Periph does not have compass priorities only devids, this allows the params to still be loaded.
> HardwareReport: deal with periph compass params

- HardwareReport/HardwareReport.js
Currently on linux boards we show the flight controller section with nothing in it because 0 is the default value. 
This treats 0 as invalid so that section is not shown unless a flight controller string can be parsed from messages.
> Hardware Report: treat board ID of 0 as invalid

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
This adds a clock drift plot:
Based on:
https://github.com/ArduPilot/pymavlink/pull/938
This is much more noisy that I would have expected. I'm not sure why.
> HardwareReport: add clock drift plot

- FilterReview/FilterReview.js
- FilterTool/filters.js
- HardwareReport/HardwareReport.js
- Libraries/Param_Helpers.js
- LogFinder/LogFinder.js
- LogFinder/index.html
- MAGFit/magfit.js
JavaScript does not have floats, so all param values are stored as floats, since some numbers are not representable exactly we sometimes get mad values that could not be represented by a float. EG:
We now get much more sensible numbers:
This also changes to sort any param download files alphabetically, this makes them easyer to diff against one another and param files from mission planner.
> all: make param nicer strings and sort param downloads alphabetically

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
@IamPete1 I have added the GPS sections in the page for this issue #72 . Please have a look, if it needs any change.
> HardwareReport: Added GPS

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
This adds plots showing the UART data rates (logging is only in master):
It also adds DroneCAN frame rates:
It would be nice to also plot a limit value based on the bit rate, but its complicated to go from a bit rate to a frame rate.
> Hardwarereport: add UART and DroneCAN data rate plots

- HardwareReport/HardwareReport.js
Fixes the plotting of rangefinder positions.
> HardwareReport: fix rangefinder pos plot and check for invalid pos

- HardwareReport/HardwareReport.js
Adds a very pessimistic limit to the DroneCAN fames/s plot. It also adds a little paragraph on why the limit is very pessimistic.
Does not try for CANFD.  We could add that in the future, bit it is more complicated again.
> HardwareReport: add CAN frame rate limit

- Libraries/DecodeDevID.js
As mentioned in this PR https://github.com/ArduPilot/ardupilot/pull/27249 . Add BMP581 to baro type of DecodeDevID.
> Libraries: decode devid: add BMP581

- HardwareReport/HardwareReport.js
- HardwareReport/index.html
- Libraries/LogHelpers.js
- LogFinder/LogFinder.js
- LogFinder/index.html
This adds a helper to get version and board details to both hardware report and log finder. This allows hardware report to extract the version from older logs.
> Add helper to get firmware and board version details from a log

- FilterReview/FilterReview.js
- FilterReview/index.html
- HardwareReport/HardwareReport.js
- HardwareReport/index.html
- Libraries/LogHelpers.js
- Libraries/OpenIn.js
- LogFinder/LogFinder.js
- MAGFit/index.html
- MAGFit/magfit.js
- PIDReview/PIDReview.js
- PIDReview/index.html
- StreamStats/StreamStats.js
- StreamStats/index.html
This adds a basic check that the required messages are present in a log before the open in button is enabled for a given log. 
For example if a log does not have `GYR` or `ISBD` then opening in filter review will not work. Currently you can click it only to get:
Now that option will be disabled for that log:
This is only a basic check, it does not check that there is enough data for the tool to work well for example. 
For LogFinder this does mean we store the list of messages for each log, so it will use a more memory. We could re-open the log on hover over like we do for the map, but this is much slower. If we were to do the per tool check at first we could only store a true/false for each tool which would save on memory but result in the logic being in a bit of a odd place.
> All: only allow open in in tools that might work with the given log

- FilterReview/FilterReview.js
With the new log primary only options a rapid EKF land switch can result in a sensor only being primary momentarily. If that is not long enough to be considered a valid batch then the tool falls over because its not expecting a sensor instance with no data. This just deletes the instance in that case.
> FilterReview: Rawlogging: remove instance if no valid data is found

- FilterReview/FilterReview.js
This fixes a typo, it was causing a error rather than the alert.
> FilterReview: fix alert typo

- LogFinder/LogFinder.js
Only the flight distance column was doing totals so the others returned NaN. The fix is to stop doing the sum if there is only a single item.
Before:
After:
> LogFinder: fix hiding of totals row for single item

- FilterReview/FilterReview.js
- FilterReview/index.html
- FilterReview/params.json
This adds support for 4.6 filtering as updated by https://github.com/ArduPilot/ardupilot/pull/25442. 
The key change is that notches are faded out with a low source frequency rather than being held at the min frequency.
> FilterReview: add support for new version of AP notch logging

- LogFinder/LogFinder.js
Saves a little loading time when showing a map for the second time.
> LogFinder: only generate map on first show

- Dev/index.html
- TelemetryDashboard/TelemetryDashboard.js
- TelemetryDashboard/index.html
Turns out MissionPlanner already forwards a stream, this adds autoconnection to `ws://127.0.0.1:56781`.
> TelemetryDashboard: Auto connect to MissionPlanner

- AnalyticTune/AnalyticTune.js
There was an error in the signal used to calculate the rate controller frequency response.  This PR fixes that error.
> Analytic Tune: Fix for rate controller frequency response calculation

- FilterReview/tracking/Logged.js
This spread was resulting in passing too many arguments to the max method. Swapping iterating over the list removes the issue. https://github.com/ArduPilot/WebTools/issues/195
> FilterReview: tracking: logged notch: remove array spread to remove large call stack

- HardwareReport/HardwareReport.js
- Libraries/LogHelpers.js
Commits with leading zeroes in SHA would lose them in the number to string conversion, leading to a false-negative GitHub check
> Libraries: Ensure SHA padding

- ThrustExpo/ThrustExpo.css
- ThrustExpo/ThrustExpo.js
- ThrustExpo/index.html
- This messes with the formatting a little, everything gets wider and param tables go side by side. Hover thrust is always shown.
This is really just a change to be more as I like it, also happy to not change it. 
- Fixes a few items missing on the reset call. If you hit example and then reset the spin arm/min/max lines remained The bottom plot was not cleared. 
- Adds the generic error catcher that pops a alert with info on how to report the issue.
- Use `param_to_string` from `Libraries/Param_Helpers.js` This limits the resolution of the saved params. For example of you click example and then save currently you get:
```
MOT_THST_EXPO,0.38500000000000106
```
Now you get:
```
MOT_THST_EXPO,0.385
```
> ThrustExpo: small updates to layout, fix couple of items missing in reset and add error catcher

- HardwareReport/HardwareReport.js
This could cause the refence point to be incorrect.
Before:
After:
> HardwareReport: Clock Drift: make sure week and time of week are valid

- AnalyticTune/AnalyticTune.js
- AnalyticTune/index.html
- AnalyticTune/params.json
This PR contains the additional calculations to determine predicted attitude Disturbance Rejection Bandwidth, attitude control with no feedforward path, and attitude stability (broken loop).  A calculation was also added for attitude control without feedforward path.  
This is all available to be plotted.  just need to add the plotting options.
I think the attitude control with and without feedforward should be set based on the SID axis. SID axes 1,2, and 3 would use the calculated and predicted attitude control with feedforward.  SID axes 4, 5 and 6 would use the calculated and predicted attitude control with no feedforward.
The predicted DRB and predicted stability should be available to display with any SID axis selected.
The calculated DRB is only available when SID Axes 4, 5, and 6 …
> Analytic Tune:  Add more predictive capability

- AnalyticTune/AnalyticTune.js
- AnalyticTune/index.html
A couple of UI updates. 
- Sets get axis names and shorter times.
Before:
After:
- Top timestamps get a bit more room.
Before:
After:
- This also links the frequency axis of the plots. So if you zoom on one plot the others update to match.
> AnalytictTune: a couple of fixups 

- LogFinder/LogFinder.js
This PR resolves issue #232 by properly scoping the loop variable in LogFinder.js. 
The implicit global variable has been replaced with a let declaration.
> fixed implicit global variable in LogFinder.js

- HardwareReport/HardwareReport.js
This PR addresses issue #233. about a performance warning in the Hardware Report Tool related to frequent readback operations on a `<canvas>`.
To fix it I added a function `configurePlotlyCanvas()` in `HardwareReport.js`. This function overrides `HTMLCanvasElement.prototype.getContext` to ensure that when a 2d context is requested, the `willReadFrequently` attribute is always set to `true`.
To test it, I verified that the hardware report tool still functions correctly with a couple of log files I generated from SITL. I also confirmed that the console warning is no longer displayed.
Let me know if any adjustments are needed.
> HardwareReport: Optimize canvas readback performance by setting willReadFrequently

- AnalyticTune/AnalyticTune.js
- AnalyticTune/index.html
This PR adds a checkbox that allows the user to select the use of the attitude response instead of the Raw Gyro for calculation of the bare airframe and rate controller frequency responses in order to improve coherence.  The calculate button must be clicked after selection of this checkbox.
> AnalyticTune: Enable use of Attitude to improve coherence for bare airframe and rate controller freq responses

- FilterReview/tracking/Throttle.js
Don't try and populate per motor throttle tracking if there is no logged RC outputs.
Fixes https://github.com/ArduPilot/WebTools/issues/246
> FilterReview: Throttle tracking: fix for no logged RCOutput

- HardwareReport/HardwareReport.js
> HardwareReport: improve formatting if flightcontroller name is not found

- Libraries/DecodeDevID.js
Updating to match adjusted baro types from ardupilot/ardupilot#29122 - per @IamPete1's [review comment](https://github.com/ArduPilot/ardupilot/pull/29122/files#r2161463563).
Changes:
- Add new `MS5837_02BA` barometer
- Distinguish original MS5837 as `_30BA` variant
> Libraries: DecodeDevID: update baro types

- FilterReview/tracking/ESC.js
- FilterReview/tracking/FFT.js
- FilterReview/tracking/RPM.js
- FilterReview/tracking/Static.js
- FilterReview/tracking/Throttle.js
This is to bring the tool in-line with https://github.com/ArduPilot/ardupilot/pull/28309.
Currently, if an ESC reports negative RPMs, the filter will clip the ESC notches at `INS_HNTCH_FREQ`:
This PR allows the notches to track correctly again:
This is applied only as an option of 4.6 (v2 filters).
> FilterReview: Allow for negative RPMs

- FilterReview/tracking/Logged.js
Adds a check that the name exists in the log message before trying to use it.
> FilterReview: deal with the case of more filters than message items
