ArduPilot/WebTools

FilterReview/index.html, FilterTool/index.html
This fixes up the labels, this means if you click on the label the item it labels get selected.
=> Fixup labels

FilterReview/FilterReview.js
This moves to use custom functions for complex maths, this saves about 20% of the transfer function calculation time. Also a couple of other fixes.
=> Filter review: DIY complex math and other fixes 

FilterReview/FilterReview.js, FilterReview/index.html
Moves to using this fft lib, https://github.com/indutny/fft.js much faster than tensorflow. Also pre allocates arrays for faster transfer function evaluation.
=> FilterReview: move to fft.js for faster fft and pre allocate arrays

FilterReview/FilterReview.js, FilterReview/index.html
A few updates reworks layout and adds range to the bode plots.
Plot moves down so its closer to the filter params.
Spectogram comes next:
Bode adds a range of filter movement. This allows so see the worst case phase lag. Note that they are only calculated for the batch center points, not over the whole log.
=> FilterReview: updates

FilterReview/FilterReview.js, FilterReview/index.html
Adds optional notch tracking lines to the FFT plot.
=> FilterReview: add notch tracking to FFT plot

FilterReview/FilterReview.js, FilterReview/index.html
Adds a flight data plot showing roll, pitch, throttle and altitude. This allows the user to pick a fairly "stable" portion of the flight.
=> FilterReview: add flight data plot for setting time range of analysis

FilterReview/FilterReview.js
=> FilterReview: NotchTarget: ref == 0 bug fix

FilterReview/FilterReview.js
Means the flight data plot still works if `POS`/`ATT`/`RATE` are missing.
=> FilterReview: check for valid data before trying to plot flight data

FilterReview/FilterReview.js, FilterReview/index.html
This should be faster as we no longer load messages we don't need.
=> FilterReview: update to latest version of log parser

FilterReview/FilterReview.js
Fixes a bug with FFT as configured notch source with no FFT data in log. Generally does a better job of handling missing data and invalid configs.
=> FilterReview: don't crash on missing tracking data, continue and alert user

FilterReview/FilterReview.js
https://github.com/ArduPilot/WebTools/pull/23 worked locally but not on the server, hopefully this will fix.
=> FilterReview: fixup filtertool URL generation

FilterReview/FilterReview.js
This fixes https://github.com/ArduPilot/WebTools/issues/25 the IMU rate is now parsed and the tool works as normal. The same bug is also present if raw sensor logging is used, I have also "fixed" that but I have not yet generated a single IMU raw sensor log to confirm that is resolved.
=> FilterReview: fix parsing of single IMU instance

FilterReview/FilterReview.js
This means we now match the pymavlink tool (sort of it is in deg/s and this in rad/s) and MATLAB's `pwelch` function for PSD.
=> FitterReview: correct averaging to get amplitude right for dB and PSD

FilterReview/FilterReview.js
A bug fix for single peek tracking from inflight FFT.
=> FilterReview: fix FFT notch tracking

FilterReview/FilterReview.js
This improves handling of raw sensor logs with gaps (gaps are expected in batch logs), such as those from a momentary drop in logging, or a second flight in the same log. 
Currently the data is processed in a single large batch for the whole log, if there are several flights this misaligns the IMU data relative to the notch tracking data, and lowers the average sample rate and thus the frequency bins also come out wrong.
Before:
After:
This also results in better handling of small gaps, these show up as broad band noise currently.
Before:
After, all except central one is removed, some more experimenting with gap thresholds might improve the result further:
Some future work would be to mark the gaps in data on the spectrogram by removing the plot for that section rather than stretching it …
=> FilterReview: better deal with gaps in raw sensor logging

FilterReview/FilterReview.js
This is a follow up from https://github.com/ArduPilot/WebTools/pull/34 we now better display gaps in logging. This:
Becomes:
=> FilterReview: improve visualization of log gaps in spectogram

HardwareReport/HardwareReport.js
Per @rmackay9 's request this adds compass external to the hardware report.
=> HardwareReport: add compass external

FilterReview/index.html, FilterTool/index.html, HardwareReport/index.html
This adds an alert on error, this makes it more obvious to the user that there is a problem. It also prompts the most likely fix, a hard reload of the page. 
For example:
=> All: Add error alert to prompt hard re-load and reporting

FilterReview/FilterReview.js, FilterReview/index.html, FilterTool/index.html, HardwareReport/index.html
Fix for https://discuss.ardupilot.org/t/fft-filter-tool-upload-issues/106559
=> FilterReview: bug fix

FilterReview/FilterReview.js
Fix for https://discuss.ardupilot.org/t/fft-filter-tool-upload-issues/106559/4 / https://discord.com/channels/674039678562861068/998764260257693706/1153250124991049768
=> FilterReview: fix for single IMU and suppress tracking warning for disabled notch

Libraries/Array_Math.js, PIDReview/PIDReview.js, PIDReview/Readme.md, PIDReview/index.html
New tool to show PID's in frequency domain and estimate step response. 
https://youtu.be/93PWYB5YzFk
Based on https://github.com/Plasmatree/PID-Analyzer and https://github.com/bw1129/PIDtoolbox
This advice should apply for generating good logs. https://youtu.be/NPS3aJqoFko?si=tR-r1j2UsZ8utKEk
=> Add PIDReview tool

FilterReview/index.html, FilterTool/index.html, HardwareReport/index.html, PIDReview/index.html
This means lazy people, such as myself, can middle click the title to open in a new tab to load a second log ect.
=> Make all titles self-link

FilterReview/FilterReview.js, FilterReview/index.html, Libraries/fft.js, PIDReview/PIDReview.js, PIDReview/index.html
Just cuts down on code duplication, should be not change in result.
=> FilterReview, PIDReview: move shared fft code to new fft file in libraries

Libraries/OpenIn.js
Follow up to https://github.com/ArduPilot/WebTools/pull/50, I just messed up the local paths, this should fix.
=> Libraries: OpenIn: fix local paths

PIDReview/PIDReview.js
Should fix https://github.com/ArduPilot/WebTools/issues/52
Now correctly detects and shows all param changes:
Future enhancement would be to group param changed that happen in a short time together. So this log would only show as three param sets. To do this param sets would have to gain a end time.
=> PIDReview: lots of bug fixes

PIDReview/PIDReview.js
Follow up to https://github.com/ArduPilot/WebTools/pull/53. Firstly this consolidates param changes that happen in very short periods to a single group. Currently setting multiple params at once will result in a new group for each param changed. This combines param changes that happen within a second. This minimuses the number of param groups with no data.
Secondly this adds highlights to the time-domain plots for param sets and matches those colors to the step plots.
=> PIDReview: consolodate fast param changes and hilight colors

HardwareReport/HardwareReport.js, PIDReview/PIDReview.js
=> PIDReview, HardwareReport: bug fixes

FilterReview/FilterReview.js
Changes needed for https://github.com/ArduPilot/ardupilot/pull/24311
=> FilterReview: allow pre-post raw logging and better deal with param changes

FilterReview/FilterReview.js
Fix for https://github.com/ArduPilot/WebTools/issues/60 where there are lots of big gaps in the log so we can't make up to the set window size. We can't magically fix but hopefully the new warning will help users figure out the issue.
=> FilterReview: don't error out for no valid data, give warning

FilterReview/FilterReview.js, Libraries/ParameterMetadata.js
Fixes https://github.com/ArduPilot/WebTools/issues/58
Last bit is now calculated correctly:
=> FilterReview: ParamerterMetadata: corectly deal with bitmask types

FilterReview/FilterReview.js, FilterReview/index.html, FilterTool/filters.js, FilterTool/index.html, HardwareReport/HardwareReport.js, HardwareReport/index.html, Libraries/Array_Math.js, Libraries/Param_Helpers.js, Libraries/ParameterMetadata.js, Libraries/Plotly_helpers.js, PIDReview/PIDReview.js, PIDReview/index.html
This is the general tidying up prior to from https://github.com/ArduPilot/WebTools/pull/61
=> All: Updates and move duplicate code to libraries 

FilterReview/FilterReview.js
Before we over estimate the effect of the filtering by 20db+, and loose the last point as 0 exactly which messes up the db calc:
After a bit of a under estimate 15 db or so and we gain back the last point:
The whole quantization noise thing is only to try and match the logged post filter, it only makes a difference at very low amplitudes. 
This is already done for batch logging where the effect is more pronounced due to the 16 bit logging.
=> FilterReview: add quantization noise estimate for raw log

index.html
More typos from me, fixes two links.
=> LandingPage: more fixups

MAGFit/magfit.js
Fix for bug in https://github.com/ArduPilot/WebTools/pull/84
=> MAGFit: fix battery current all zero check

MAGFit/magfit.js
This trivial fix had been sat on my local branch for ages waiting to go in with something else.
No more bugs, so might as well merge now....
=> MAGFit: fit earth field console log

HardwareReport/HardwareReport.js, HardwareReport/index.html
Adds links to download embedded files.
=> HardwareReport: add download of embedded files

HardwareReport/HardwareReport.js, HardwareReport/index.html
This includes most of https://github.com/ArduPilot/WebTools/pull/93, some improved labels and a extra description for minimal params. This also fixes the hiding/showing of the changes param options.
=> HardwareReport: add more info on params

MAGFit/magfit.js
Hides a empty plot if there are no motor compensation sources.
=> MAGGit: hide "Motor compensation sources" if there are none

HardwareReport/HardwareReport.js, HardwareReport/index.html
Adds expandable table for each param to show changes with timestamp.
=> HardwareReport: show parameter changes during log

HardwareReport/HardwareReport.js, HardwareReport/index.html
Adds dropped packets and free buffer to log stats:
Also adds decoding of WDOG meassages:
=> HardwareReport: add watchdog decode and plot dropped log packets and buffer.

HardwareReport/HardwareReport.js, HardwareReport/index.html
Adds a IOMCU section populated from the `IOMC` log.
=> HardwareReport: add IOMCU error check

HardwareReport/HardwareReport.js
User can now download rally points from the log as is already possibly for mission and fence.
=> HardwareReport: add download of rally points

FilterReview/FilterReview.js
Currently the time range is just the full log. This changes to start at the first none zero throttle and end at the last none zero throttle. If throttle can't be found then the full range is used as before.
This gives better results for those who were not aware they should pick a section of the flight. We could get very complicated trying to pick a section automatically using altitude too. But I think its better to keep it simple. It is also easier to manually zoom in further than to manually zoom out so were better to stay a little on the loose side.
=> FilterReview: auto zoom based on none zero throttle

MAGFit/index.html, MAGFit/magfit.js
This adds a short intro to the page and some tool tips giving more information.
=> MAGFit: add tippy tool tips

HardwareReport/HardwareReport.js
Handy for testing https://github.com/Williangalvani/JsDataflashParser/pull/10
=> HardwareReport: add log load timer for performance checking.

HardwareReport/HardwareReport.js
A couple of things got broken by the resent parser re-work.
=> HardwareReport: fix CAND and IMU temp

FilterReview/FilterReview.js, HardwareReport/HardwareReport.js, MAGFit/magfit.js, PIDReview/PIDReview.js
=> Convert over to new `get` log parser method

HardwareReport/HardwareReport.js
Adds support for the new driver instance field from https://github.com/ArduPilot/ardupilot/pull/26226
Also now prints unique IDs.
=> HardwareReport: add support for CAND driver instance field

HardwareReport/HardwareReport.js
This fixes a dumb bug in https://github.com/ArduPilot/WebTools/pull/136.
=> HardwareReport: fix compass parsing

FilterReview/FilterReview.js, FilterReview/index.html, HardwareReport/HardwareReport.js, HardwareReport/index.html, KinematicTool/index.html, Libraries/OpenIn.js, LogFinder/LogFinder.js, LogFinder/index.html, MAGFit/index.html, MAGFit/magfit.js, PIDReview/PIDReview.js, PIDReview/index.html, StreamStats/index.html
This makes open in faster and more reliable. Unfortunately we can't hook "plot.ardupilot" in the same way because it has a different origin.
=> Openin: hook loaded event for other webtools for faster load.

LogFinder/LogFinder.js
A few updates.
Page title now shows the opened directory:
Boards show common path between all log:
New param changes column shows a change count and holds the full diff hover-over.
Totals column show total size, flight time and the param diff from first to last log:
=> LogFinder: updates

Libraries/DecodeDevID.js
added SCHA63T to imu types of DecodeDevID.
https://github.com/ArduPilot/ardupilot/pull/26871
=> Libraries: decode devid: add SCHA63T

Libraries/OpenIn.js
Passing the file handle means the tool that the file is opened in can:
1. Display the file name, hopefully avoiding confusion.
2.  Allow open in recursively rather than having to go back to the tool the file was first opened with.
This also makes open in asyc, so the original page does not lock up wile the second page loads. 
I would like to allow opening tabs in the background and setting the tab order, but this seems not to be possible in all browsers.  
Next step is to add the file names to the page titles so that things are easyer to track if you have several files open.
=> OpenIn: pass file handle for local tools and make async

FilterReview/FilterReview.js, FilterReview/index.html, HardwareReport/HardwareReport.js, HardwareReport/index.html, MAGFit/index.html, MAGFit/magfit.js, PIDReview/PIDReview.js, PIDReview/index.html
Adds the file name to the page title so it can be seen in the tab:
=> All: report log file name in page title

FilterReview/index.html, FilterTool/index.html, HardwareReport/index.html, KinematicTool/index.html, LogFinder/index.html, MAGFit/index.html, PIDReview/index.html, StreamStats/index.html
Now were tending to run stuff async were missing errors that should be reported.
=> All: catch "unhandledrejection" from Promises

MAGFit/Readme.md
This adds a write up of how the maths works. Can be viewed here: https://github.com/IamPete1/WebTools/tree/magfit_doc/MAGFit#magfit
=> MAGFit: add write up of method

HardwareReport/HardwareReport.js, index.html
Fix bugs from https://github.com/ArduPilot/WebTools/pull/159 and https://github.com/ArduPilot/WebTools/pull/160
=> Fix bugs from https://github.com/ArduPilot/WebTools/pull/159 and https://github.com/ArduPilot/WebTools/pull/160

RotationCheck/index.html
Fixup from https://github.com/ArduPilot/WebTools/pull/168
=> RotationCheck: fixup plot margin

LogFinder/LogFinder.js, LogFinder/index.html
This adds a flight distance column and popup map of the path. This makes it easyer to check if the log is the one your looking for.
=> LogFinder: add flight distance column and popup map

HardwareReport/HardwareReport.js
Plotting both master and slave antenna positions is useful for debugging moving base line for yaw.
=> HardwareReport: add plottting of GPS master and slave postions for moving baseline

HardwareReport/HardwareReport.js
Adds a version check for AP periph nodes on the DroneCAN. Works the same as the one for the main firmware. 
Also improves handling of API rate limit, its still quite hard to hit but this does make it more likely.
=> HardwareReport: add AP_Periph version check

SysID/index.html
This PR provides the following improvements to give a better user experience and functionality
-Add multiplier and gravity compensation for outputs in the transfer function solver feature
-made the time and frequency start and end, as well as, the cut off frequency for the low pass filter conditioner as common fields between the two solvers
-Added pre-population capability for State Space solver.  This populates the fields for common Sys ID model structures.  At this point only the multirotor model structures were added.
-Indentation format was corrected throughout
This was tested against the X8-M dataset.
=> SysID: Added improvements for user friendliness and functionality

FilterReview/FilterReview.js
This adds support for the new instance RPM log added to AP in https://github.com/ArduPilot/ardupilot/pull/27306
=> FilterReview: RPM tracking: add support for new RPM message

HardwareReport/HardwareReport.js, HardwareReport/index.html, LogFinder/LogFinder.js
Example of what we could do, just need to come up with some wording and somewhere to send users to make a report.
=> HardwareReport: add alert if crash dump found

FilterReview/FilterReview.js, FilterReview/index.html, Libraries/fft.js, PIDReview/PIDReview.js, PIDReview/index.html
Removes two copy's of the same function in favour of one in the fft lib. This saves adding a third copy in https://github.com/ArduPilot/WebTools/pull/188
=> FilterReview, PIDReview: add and use window size increment helper

FilterReview/FilterReview.js, Libraries/fft.js, PIDReview/PIDReview.js
Removes more duplicated code ready for https://github.com/ArduPilot/WebTools/pull/188
=> FilterReview, PIDReview: add fft scale helpers

FilterReview/FilterReview.js
Fixes the issue reported in https://discuss.ardupilot.org/t/filter-tool-help/124852
=> FilterReview: check for instances in IMU message

AnalyticTune/AnalyticTune.js
This PR fixes the save parameter routine to save the INS parameters and only the ATC params for the axis of interest.
I have not checked the load parameters button.  @IamPete1 Do you think this is necessary.  Also do you think the link button is necessary.
=> AnalyticTune: fix the save parameter routine

FilterReview/FilterReview.js
Fixes https://github.com/ArduPilot/WebTools/issues/199. Trying to set a const causes a error.
=> FilterReview: remove set of const with both post and pre+post logging

FilterReview/FilterReview.js
Fixes https://github.com/ArduPilot/WebTools/issues/206
=> FilterReview: spectogram remove array spread to reduce call stack

TelemetryDashboard/Widgets/SubGrid.js
This allows a background image to a subgrid, this means you can do things like this:
Image is optionally added in the widget settings:
Object fit "contain" is used so the image retains its original aspect ratio. The sub grid is also resized to this fixed aspect ratio, this allows items to be placed relative to the image without there position being lost as the dashboard is scaled. Could also add the option to use object fit "fill" which would scale the image to fit the widget, but I think if your adding a image you want the aspect ratio to be correct.
=> TelemetryDashboard: SubGrid: optional background image

Libraries/DecodeDevID.js
Pending https://github.com/ArduPilot/ardupilot/pull/28383
=> DecodeDevID: added IIM42653

HardwareReport/HardwareReport.js, HardwareReport/index.html
This adds a plot of the power flags.
=> HardwareReport: add power flags plot

HardwareReport/HardwareReport.js
Fixup for https://github.com/ArduPilot/WebTools/pull/220
Older version use different filed names.
=> HardwareReport: Powerflags: deal with old POWR field names

FilterReview/tracking/Throttle.js
If the is no current sensor the logged resting voltage is always 0. However when used internally the larger of the raw and resting voltage is returned. This adds that and fixes a bug in the low voltage case. The battery scale was resulting in the frequencies being calculated as if the battery were at MOT_BAT_VOLT_MIN. 
A comparison between estimated centre frequencies and logged shows the issue.
Before:
After:
Still not perfect, but RC output logging is only 10Hz.
=> FilterReview: tracking: Throttle: fix pre-motor tracking with no current sensor

Readme.md
Clone in 1 step instead of 2 :)
=> Simplify clone using recurse on clone

FilterReview/FilterReview.js
Fix for:
https://discuss.ardupilot.org/t/fft-filter-tool-upload-issues/106559/6
=> FilterReview: don't try and plot without data

HardwareReport/HardwareReport.js
A DroneCAN port:
A Networking port:
=> hardwareReport: UART: add missing protocols and support DroneCAN and Networking ports

FilterReview/tracking/Throttle.js
Fixes https://github.com/ArduPilot/ardupilot/issues/30528
=> FilterReview: Tracking: Throttle: only dynamic if config is provided

HardwareReport/HardwareReport.js
To go with https://github.com/ArduPilot/ardupilot/pull/31162
=> HardwareReport: support upto 6 airspeed sensors
